var HttpWebHooksPlatform = require('./src/homekit/HttpWebHooksPlatform');
var HttpWebHookSensorAccessory = require('./src/homekit/accessories/HttpWebHookSensorAccessory');
var HttpWebHookSwitchAccessory = require('./src/homekit/accessories/HttpWebHookSwitchAccessory');
var HttpWebHookPushButtonAccessory = require('./src/homekit/accessories/HttpWebHookPushButtonAccessory');
var HttpWebHookLightBulbAccessory = require('./src/homekit/accessories/HttpWebHookLightBulbAccessory');
var HttpWebHookThermostatAccessory = require('./src/homekit/accessories/HttpWebHookThermostatAccessory');
var HttpWebHookOutletAccessory = require('./src/homekit/accessories/HttpWebHookOutletAccessory');
var HttpWebHookSecurityAccessory = require('./src/homekit/accessories/HttpWebHookSecurityAccessory');
var HttpWebHookGarageDoorOpenerAccessory = require('./src/homekit/accessories/HttpWebHookGarageDoorOpenerAccessory');
var HttpWebHookStatelessSwitchAccessory = require('./src/homekit/accessories/HttpWebHookStatelessSwitchAccessory');
var HttpWebHookLockMechanismAccessory = require('./src/homekit/accessories/HttpWebHookLockMechanismAccessory');
var HttpWebHookWindowCoveringAccessory = require('./src/homekit/accessories/HttpWebHookWindowCoveringAccessory');
var HttpWebHookFanv2Accessory = require('./src/homekit/accessories/HttpWebHookFanv2Accessory');
var HttpWebHookCarbonDioxideSensoryAccessory = require('./src/homekit/accessories/HttpWebHookCarbonDioxideSensorAccessory');
var HttpWebHookValveAccessory = require('./src/homekit/accessories/HttpWebHookValveAccessory');

module.exports = function(homebridge) {
  homebridge.registerPlatform("homebridge-HST-http-webhooks", "HSTHttp", HttpWebHooksPlatform);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpSensor", HttpWebHookSensorAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpSwitch", HttpWebHookSwitchAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpPushButton", HttpWebHookPushButtonAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpLight", HttpWebHookLightBulbAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpThermostat", HttpWebHookThermostatAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpOutlet", HttpWebHookOutletAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpSecurity", HttpWebHookSecurityAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpGarageDoorOpener", HttpWebHookGarageDoorOpenerAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpStatelessSwitch", HttpWebHookStatelessSwitchAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpLockMechanism", HttpWebHookLockMechanismAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpWindowCovering", HttpWebHookWindowCoveringAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpFanv2", HttpWebHookFanv2Accessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpCarbonDioxideSensor", HttpWebHookCarbonDioxideSensoryAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpValve", HttpWebHookValveAccessory);
};
