var HttpWebHooksPlatform = require('./src/homekit/HttpWebHooksPlatform');
var HttpWebHookSensorAccessory = require('./src/homekit/accessories/HttpWebHookSensorAccessory');
var HttpWebHookSwitchAccessory = require('./src/homekit/accessories/HttpWebHookSwitchAccessory');
var HttpWebHookPushButtonAccessory = require('./src/homekit/accessories/HttpWebHookPushButtonAccessory');
var HttpWebHookLightBulbAccessory = require('./src/homekit/accessories/HttpWebHookLightBulbAccessory');
var HttpWebHookThermostatAccessory = require('./src/homekit/accessories/HttpWebHookThermostatAccessory');
var HttpWebHookOutletAccessory = require('./src/homekit/accessories/HttpWebHookOutletAccessory');
var HttpWebHookSecurityAccessory = require('./src/homekit/accessories/HttpWebHookSecurityAccessory');
var HttpWebHookGarageDoorOpenerAccessory = require('./src/homekit/accessories/HttpWebHookGarageDoorOpenerAccessory');
var HttpWebHookStatelessSwitchAccessory = require('./src/homekit/accessories/HttpWebHookStatelessSwitchAccessory');
var HttpWebHookLockMechanismAccessory = require('./src/homekit/accessories/HttpWebHookLockMechanismAccessory');
var HttpWebHookWindowCoveringAccessory = require('./src/homekit/accessories/HttpWebHookWindowCoveringAccessory');
var HttpWebHookFanv2Accessory = require('./src/homekit/accessories/HttpWebHookFanv2Accessory');
var HttpWebHookCarbonDioxideSensoryAccessory = require('./src/homekit/accessories/HttpWebHookCarbonDioxideSensorAccessory');
var HttpWebHookValveAccessory = require('./src/homekit/accessories/HttpWebHookValveAccessory');

module.exports = function(homebridge) {
  homebridge.registerPlatform("homebridge-HST-http-webhooks", "HttpWebHooks", HttpWebHooksPlatform);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HttpWebHookSensor", HttpWebHookSensorAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HttpWebHookSwitch", HttpWebHookSwitchAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HttpWebHookPushButton", HttpWebHookPushButtonAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HttpWebHookLight", HttpWebHookLightBulbAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HttpWebHookThermostat", HttpWebHookThermostatAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HttpWebHookOutlet", HttpWebHookOutletAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HttpWebHookSecurity", HttpWebHookSecurityAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HttpWebHookGarageDoorOpener", HttpWebHookGarageDoorOpenerAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HttpWebHookStatelessSwitch", HttpWebHookStatelessSwitchAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HttpWebHookLockMechanism", HttpWebHookLockMechanismAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HttpWebHookWindowCovering", HttpWebHookWindowCoveringAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HttpWebHookFanv2", HttpWebHookFanv2Accessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HttpWebHookCarbonDioxideSensor", HttpWebHookCarbonDioxideSensoryAccessory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HttpWebHookValve", HttpWebHookValveAccessory);
};
