var HSTHttpPlatform = require('./src/homekit/HSTHttpPlatform');
var HSTHttpSensor = require('./src/homekit/accessories/HSTHttpSensorAccessory');
var HSTHttpSwitch = require('./src/homekit/accessories/HSTHttpSwitchAccessory');
var HSTHttpPushButton = require('./src/homekit/accessories/HSTHttpPushButtonAccessory');
var HSTHttpLightBulb = require('./src/homekit/accessories/HSTHttpLightBulbAccessory');
var HSTHttpThermostat = require('./src/homekit/accessories/HSTHttpThermostatAccessory');
var HSTHttpOutlet = require('./src/homekit/accessories/HSTHttpOutletAccessory');
var HSTHttpSecurity = require('./src/homekit/accessories/HSTHttpSecurityAccessory');
var HSTHttpGarageDoorOpener = require('./src/homekit/accessories/HSTHttpGarageDoorOpenerAccessory');
var HSTHttpStatelessSwitch = require('./src/homekit/accessories/HSTHttpStatelessSwitchAccessory');
var HSTHttpLockMechanism = require('./src/homekit/accessories/HSTHttpLockMechanismAccessory');
var HSTHttpWindowCovering = require('./src/homekit/accessories/HSTHttpWindowCoveringAccessory');
var HSTHttpFanv2 = require('./src/homekit/accessories/HSTHttpFanv2Accessory');
var HSTHttpCarbonDioxideSensory = require('./src/homekit/accessories/HSTHttpCarbonDioxideSensorAccessory');
var HSTHttpValve = require('./src/homekit/accessories/HSTHttpValveAccessory');

module.exports = function(homebridge) {
  homebridge.registerPlatform("homebridge-HST-http-webhooks", "HSTHttp", HSTHttpPlatform);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpSensor", HSTHttpSensor);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpSwitch", HSTHttpSwitch);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpPushButton", HSTHttpPushButton);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpLight", HSTHttpLightBulb);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpThermostat", HSTHttpThermostat);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpOutlet", HSTHttpOutlet);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpSecurity", HSTHttpSecurity);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpGarageDoorOpener", HSTHttpGarageDoorOpener);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpStatelessSwitch", HSTHttpStatelessSwitch);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpLockMechanism", HSTHttpLockMechanism);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpWindowCovering", HSTHttpWindowCovering);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpFanv2", HSTHttpFanv2);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpCarbonDioxideSensor", HSTHttpCarbonDioxideSensory);
  homebridge.registerAccessory("homebridge-HST-http-webhooks", "HSTHttpValve", HSTHttpValve);
};
